### ISSUE TITLE
Any known good Docker containers

### ISSUE THREAD

**Issue by anxiousmodernman** [Xorlev/gatekeeper#26]
I use a version of this lib in my tests, and it would be convenient to use a docker container.

Are there any known Docker containers that wrap up nginx + jvm + gatekeeper, but do not include zookeeper?

**Comment by Xorlev** [comment]
I don't currently have a Docker build, but if you'd like to contribute one I'd gladly accept it.

**Comment by anxiousmodernman** [comment]
I may be able to give this a shot. But I'm basically nowhere with it at the moment. I am developing a service that is going to sit *behind* a gatekeeper+nginx at the edge. Right now I am hardcoding the nginx config, just to get things going. I have an nginx container, but no gatekeeper.

To dockerize this project, I'd recommend:

* a container with nginx + gatekeeper bundled together
* a way to mount appropriate configs from outside the container
* zookeeper running in a separate container
* docker-compose.yml for describing the dependency between gatekeeper and zookeeper

Something like
```yaml
zk:
  image: some/public/zookeeper
gatekeeper:
  build: .  # reference the Dockerfile in this project's root
  links:
    - zk    # establish a networking link to zk, bring up zk first
```

I've had trouble dockerizing Java projects before, since it's hard to avoid "baking" the configs into the container itself. On one level, this is fine, since the container is self-contained. On another level, it sucks to have to rebuild when your configs change.

I will fork and see if I can whip something up.
